version: '3.3'
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      TZ: Europe/Paris
      MONGO_INITDB_DATABASE: 'template_bdd'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Paris
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    ports:
      - "8180:1080"
      - "8125:1025"

volumes:
  mongo-data:
